sudo: required

language: node_js

services:
- docker

env:
  matrix:
  - NODE_ENV=development
  global:
  - secure: vQkI7caQnTLlt6r8iZ67ApofyinQIJ/tfrHczxAwfUGXWVtFVyH7jRbBzHQLJSCxEJ/6z209M8eO+qC+myv+EGV01b4F7kWcsz5rwWFmC5CtKoblgNUx5Fb/U/Cl9bEMz58ogj1SzRHcs0Y7vwi8YwnZDFXz2VE/OivqrwbBGvXUfkV/ywd7679tGO5e3OZGttz/Hj6+nv0ZAWBStdqASfB72B/NVjPDHPNXufb1JGgH6x2T1pSZ/lAA1wPJ/MH++Thwa8Vc5/fxBMoCTWGoQWuEbkQSEdQM4+rPx5UfC8koWl/49UylFoT7x1VffXwXLmNocv3zcweA5WEJhYepg4H1NQdRZu53FKns578/l/Z1Fnrhf/JI2gsBVfm3Gm9GOTkN+lSJtdC+aGDi0srOE0xmLmyJIZVbs6oM8jKZ0vRu1iVPES5O7Gff132HZTV5vNfqx15oPXfsCg8HyeSxvDPn0SFnV2HBpxwt7bPPxOFZ9tkSxd5oU80ppPuCp08rZii7jCsviMDIsvkZzvL3pGV2J2RETrSz3VX1+ljgoPqXg/KWj5jdcA/mPrTWZH/WoEXcX+hms7Hp85m2BP+Xu3c4XO3QUKhknTQeo/SHQBtgc0P0XVroQkzYg9OUq4sxxtUtmNnLOl9ls17nW674EWALGEVMXSpqjgGOW+tm22I=
  - GCLOUD_ID="arctic-operand-181515"
  - CLUSTER_NAME=crypto
  - ZONE="europe-west1-c"
  - TAG_NAME=cryptocrawler:latest
  - FULL_IMAGE_NAME=gcr.io/$GCLOUD_ID/$TAG_NAME
  - GCLOUD_KEY=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYXJjdGljLW9wZXJhbmQtMTgxNTE1IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMGY1MzA2MmNkNmIzMDYzMjczZTlhYmFjN2JlMThjYjA5Njg3MTg1MCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFDNVBZdXNDU1V3VWxFYVxuc00yWHU2cDFFdm5FWFZtQ3B6K2JGc0J2SXppRGV5aW1BSGk5aUttVUZlbkowWUZNdFJHZ2JBb2pKQlpweERhWFxuL0VxbDRaOTl5aG9jNmU3allvcnljRVRnM0VKL3VNck9oNTJTYzJySFJRUzBwdTc2dlZuOWxzbnJtcHVUd0VCMVxuQWZSWGlPNTRyZDhIVXJlRE9kTnhaVXNVYXIyalkzK2xBa0FrODc0b2kvZ1EwekQzSitrbnZtYW0xOGR2dXVuY1xuSXpTSFBwM2pvTlRHSjBnMkkvN2hKa2pPYldycW1RTUkyc1dJaU1vbFM4NUVPdDE3eTVXajVOTG0yL1lKcUdZZlxuWlQ2T28wRWxCb3JwalJSZWZhSG55SXlGWUpsaGowdm5nZFljcTFrK2RGdkg1VFozcFJad3RBQnMwVngveHg1NVxuVzNzZFFaYVRBZ01CQUFFQ2dnRUFCcGg3NkNpOU03N0NsNFl6RTlPQlNzRGR0dEd5RmJaWnkrNWY5TFVXMW91a1xuazJDUjdBRzVOQVlodUdkbXlMSHJ5ai8ram1qRENZb01mWlhrbklwdmtOMkkxMzIyM1U3TmJydHpvR1FIVkIvaVxuekw3RWJBb0RBOHhmMGdUZG5uenVmdHFISHdYMnd5aUZ3d1RLUy9HYXVCNU13aWgrVTBSVVZJWE1TaEpRNVVmZVxucVQ0UndUblNCMTE3YTNzT2xMWVI0M2ZJekZTdlB1bzVLaWdmRnIwWFhMR2I1VkZxK0NuUk80b2YzblZGeVVUc1xuRmd3NFRKRk8rNVF1ZDY5aXZKbFM2bGQ3VkpJWWJKTXpsb21ycVVBTC9waHhKTmRiSklZNVZRUlUvcy9sMkVBcVxuRnVPa256WDhXWVEwWVY0TUNuemFxNEdSWEt5T3Y3SGV2TG0yU25yNmNRS0JnUURlajRURW9MTUcydXBSK3hhalxuNEpQVW1rem9JZyt1cXIySDRoQUMxLzZha0xtd24zalJtQWdYRWRDRHRQV1VDMDhSZVZzSUR2RzhlMEJ4RkdEK1xuNHEzd2kra3JQaXVMQVV2VldRNzQxR2pDM2Z4aDRZd01kc1hzUGpHTXY1OWFQMm9HeE1BaTgrY1BqZUFKTHFGZVxudmpxVnlrMk1QTmZaM0JQbDdMMHJEK2hHb3dLQmdRRFZFbzdDOVQ0QUVyZkhPR2dEK3dhTVN2OUN0MDJuN08walxuTHQ0RHJaV3V3NFVOeDJ3Qkt2N1lQMDVmOE9xQ3VRaUZBbUlHeUR6ZWdMak9DTjNUMlR1SjBEOE05NU9DMGZ6K1xuU2xjZzBlYjYxV1FKMS9QZUxNcmVnRzZTS1BEem81a2pPd2YzTVhvQ2kzNGVVTS9Xa1l5YW5HUU9CaTl3Z3B4TVxudVl4N3pjeWZVUUtCZ0ZUYXpWa1dtQXRtRGU3aDE3ajFtQWQ0S1JoY1hEUlJQdC8vRGZHM25vZ1o0K0oyZXQ4V1xub3djQXNNcDJoU2REeElxNkJUNG1USDU3VTQrSm9JMnRxWG5NTGtOaGVjS081UFhiOWJ4alorbmNMeXkyak9uM1xub3ZDMnFiZXJHN3VSNy8vU3BocnRlVXhSNEhnL3dpRFlVSWZwMFBWR0FWbzc4WTQ1VzhwK1R5WVhBb0dBRnA1U1xuczFWdlVIaXNNNlRFUGUvdTRRT3hGemI0TW1SUFJCWGNrWTFpdjF1WUN6OXBNcktLdlEvelZQSHhJeEZiV3l0R1xubHF1NDhuRzlySGw2ZXR1cm0xU1U3TjUzTlVMdlZWczA1cElCc0F6cEFyWis5ODNQZDFFdzY2a1c4dlloOG9CNFxudHYvMGtNS1lEOFhLV2wrM0NrNmh2RzlocDlMbG5xdHZ3MUMwY1JFQ2dZQnBQZEtRWjZLdWZzUE4rWGFHWlUvK1xuWGZVQVhVVlZoZW92bjRrd0EyOWp3dTNwM0xGYkkzODQzVlEyOGxVRkxlNEE3RFNoTkpLa2xYNTIvMVJDSTdnZVxuTituZXJmWFdsSi9jUEtEeVJZcERENldSbVNaWENLODJ1RE02TkhVZzlZVHBjY3c1cWhxYVpiUS8ydXFwQzVDSVxudUo3WFVkdFd1MEVNdm13bFUyd3p0UT09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiYWRtaW4tYWNjb3VudEBhcmN0aWMtb3BlcmFuZC0xODE1MTUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA1MDY1MzAwNzM4NTcyNjY2ODU4IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYWRtaW4tYWNjb3VudCU0MGFyY3RpYy1vcGVyYW5kLTE4MTUxNS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=

node_js:
- '8'

cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"

before_install:
- echo $GCLOUD_KEY | base64 --decode > gcloud.json



install:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null 2>&1; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.json  
- gcloud components update kubectl --quiet
- gcloud config set project $GCLOUD_ID
- gcloud config set compute/zone $ZONE

script:
- docker build --no-cache=true -t $FULL_IMAGE_NAME .

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  gcloud docker -- push $FULL_IMAGE_NAME;
  gcloud container clusters get-credentials $CLUSTER_NAME;
  kubectl set image deployment/cryptocrawler-master master=gcr.io/arctic-operand-181515/cryptocrawler:latest;
  fi

